  [build]
    command = "cd www && hugo build --gc --minify"
    publish = "www/public"

  [build.environment]
    HUGO_VERSION = "0.147.7"
    HUGO_ENV = "production"

  [[headers]]
    for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
